# Exercise 5: Create a Matrix with Integer Variables and Constants

Create the following matrix in an NL model where x1, x2, x3 are integer variables and 5 is a constant.

Note: You can construct a matrix from a mix of variables and constants using stack or concatenate

$\begin{bmatrix}
x1 & x2 \\
5 & x3
\end{bmatrix}$

The variables should have a lower bound of -10 and upper bound of 10.
Then solve the problem such that the sum of the matrix is maximized (the sum should be 35).

## Create Model

In [1]:
# required imports
from dwave.optimization import Model, stack
from dwave.optimization.mathematical import concatenate

# create blank model
model = Model()

# create a 2d integer variable matrix of size 2 representing [[x1, x2]]
top_row = model.integer([2], lower_bound = -10, upper_bound = 10) 
print(f"Shape of top_row: {top_row.shape()}")
with model.lock():
    model.states.resize(1)
    print(f"state 0 of top_row:\n {top_row.state(0)}\n")

# create a constant of 5
five = model.constant(5)
print(f"Shape of five: {five.shape()}")
with model.lock():
    model.states.resize(1)
    print(f"state 0 of five:\n {five.state(0)}\n")


# create an integer variable representing x3
x3 = model.integer(lower_bound = -10, upper_bound = 10)
print(f"Shape of x3: {x3.shape()}")
with model.lock():
    model.states.resize(1)
    print(f"state 0 of x3:\n {x3.state(0)}")

Shape of top_row: (2,)
state 0 of top_row:
 [0. 0.]

Shape of five: ()
state 0 of five:
 5.0

Shape of x3: ()
state 0 of x3:
 0.0


In [2]:
# stack x3 and five into a 1d matrix of size 2
bottom_row = stack([x3, five])
print(f"Shape of bottom_row: {bottom_row.shape()}")
with model.lock():
    model.states.resize(1)
    print(f"state 0 of bottom_row:\n {bottom_row.state(0)}")

Shape of bottom_row: (2,)
state 0 of bottom_row:
 [0. 5.]


In [3]:
# use reshape to change top_row and bottom_row into 2d matrices
# https://docs.dwavequantum.com/en/latest/ocean/api_ref_optimization/symbols.html#dwave.optimization.model.ArraySymbol.reshape
top_row = top_row.reshape((1, 2))
print(f"Shape of top_row: {top_row.shape()}")
with model.lock():
    model.states.resize(1)
    print(f"state 0 of top_row:\n {top_row.state(0)}\n")

bottom_row = bottom_row.reshape((1, 2))
print(f"Shape of bottom_row: {bottom_row.shape()}")
with model.lock():
    model.states.resize(1)
    print(f"state 0 of bottom_row:\n {bottom_row.state(0)}")

Shape of top_row: (1, 2)
state 0 of top_row:
 [[0. 0.]]

Shape of bottom_row: (1, 2)
state 0 of bottom_row:
 [[0. 5.]]


In [5]:
# concatenate top_row and bottom row into a 2 x 2 matrix
# https://docs.dwavequantum.com/en/latest/ocean/api_ref_optimization/math.html#dwave.optimization.mathematical.concatenate
final_matrix = concatenate((top_row,bottom_row), axis=0)
print(f"Shape of final_matrix: {final_matrix.shape()}")
with model.lock():
    model.states.resize(1)
    print(f"state 0 of final_matrix:\n {final_matrix.state(0)}")

Shape of final_matrix: (2, 2)
state 0 of final_matrix:
 [[0. 0.]
 [0. 5.]]


In [6]:
# maximize the sum of the final matrix
model.minimize(-final_matrix.sum())

# Solve Problem

Send the NL Model to the LeapHybridNLSampler

In [8]:
from dwave.system import LeapHybridNLSampler
sampler = LeapHybridNLSampler()
sampler.sample(model, label = "demo model")

<Future at 0x1856fb65ed0 state=running>

# Check Results

In [9]:
with model.lock():
    model.states.resize(1)
    print(f"state 0 of final_matrix:\n {final_matrix.state(0)}")

state 0 of final_matrix:
 [[10. 10.]
 [10.  5.]]
